In [2]:
import pathlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from book_registry import books

df = pd.read_feather("../data/preprocessing/book-5_chunked88_withprev.feather")
df

,book,sentence,chapter,sentence_chapter,content,previous_sentence
0,book-5,1,1,1,This year we have taken the formations of the ...,
1,book-5,2,1,2,Those of you - I think it was the majority - w...,This year we have taken the formations of the ...
2,book-5,3,1,3,A certain number of you - I am only expressing...,Those of you - I think it was the majority - w...
3,book-5,4,1,4,Those who have had the courage to do so will b...,A certain number of you - I am only expressing...
4,book-5,5,1,5,In a way it is a modest enough ambition for me...,Those who have had the courage to do so will b...
...,...,...,...,...,...,...
3755,book-5,3756,28,118,Experience proves that we have the most contra...,"I would like in concluding, because I alluded ..."
3756,book-5,3757,28,119,I think that in fact these objections which ar...,Experience proves that we have the most contra...
3757,book-5,3758,28,120,"In fact, I believe that if something allows us...",I think that in fact these objections which ar...
3758,book-5,3759,28,121,It is at this level that the Christian command...,"In fact, I believe that if something allows us..."
3759,book-5,3760,28,122,It is the same thing again that another wisdom...,It is at this level that the Christian command...

### Sampling

In [10]:
sample_50 = df.sample(n=50, random_state=42)
sample_50.head()

,book,sentence,chapter,sentence_chapter,content,previous_sentence
1553,book-5,1554,12,14,"Abundantly expressed by all the authors, this ...",He thinks he has to put aside all its structur...
2986,book-5,2987,23,46,"The presence, the predominance of what is, whe...",This phantasy is of course far from being limi...
220,book-5,221,2,83,At first sight forgetting is not the same thin...,"Just as we have spoken about maritablement , l..."
2965,book-5,2966,23,25,It is the point from which she identifies hers...,Dora identifies herself with Mr. K. The woman ...
1971,book-5,1972,15,34,It is for this reason that there are three pol...,But this relationship to the signifying triad ...

In [6]:
sample_500 = df.sample(n=500, random_state=42)
sample_500

,book,sentence,chapter,sentence_chapter,content,previous_sentence
1553,book-5,1554,12,14,"Abundantly expressed by all the authors, this ...",He thinks he has to put aside all its structur...
2986,book-5,2987,23,46,"The presence, the predominance of what is, whe...",This phantasy is of course far from being limi...
220,book-5,221,2,83,At first sight forgetting is not the same thin...,"Just as we have spoken about maritablement , l..."
2965,book-5,2966,23,25,It is the point from which she identifies hers...,Dora identifies herself with Mr. K. The woman ...
1971,book-5,1972,15,34,It is for this reason that there are three pol...,But this relationship to the signifying triad ...
...,...,...,...,...,...,...
3752,book-5,3753,28,115,What does not seem to have been seen at all in...,"""The positive feature"", he writes, ""is precise..."
214,book-5,215,2,77,"Therefore we see, it can be a joke, it can be ...","In any case what Freud shows us, is that the m..."
2464,book-5,2465,19,21,"We are able, now that psychoanalysis is establ...",We must portray it for ourselves in its charac...
2603,book-5,2604,20,58,There we are really only at the level and at t...,"In fact there again what we rediscover, is tha..."
157,book-5,158,2,20,It is the famillionaire in so far as it deride...,"It is a type of emergence of an object, that i..."

In [12]:
# sample_50.to_csv("../data/preprocessing/book-5_chunked88_withprev_sample50.csv")
# sample_500.to_csv("../data/preprocessing/book-5_chunked88_withprev_sample500.csv")
# df.to_csv("../data/preprocessing/book-5_chunked88_withprev_nosample.csv")